### ISSUE TITLE
Client ID and Invalid credentials

### ISSUE THREAD

**Issue by brianbolnick** [RuBAN-GT/omniauth-bungie-oauth2#1]
The information in the Readme is not very helpful.  I got to the point where I am able to redirect to bungie, but there is no place to pass the client ID as a param. I hard coded it in and was able to authorize the app, but now I am getting an invalid credentials error. This is the only response I'm getting back from Bungie:

Parameters: {"message"=>"invalid_credentials", "origin"=>"https://myurl.com/signin", "strategy"=>"bungie"}

@RuBAN-GT

**Comment by RuBAN-GT** [comment]
Good day, @brianbolnick. I added an [example](https://github.com/RuBAN-GT/omniauth-bungie-oauth2#rails-integration) of how I integrated this gem with my rails. On the Bungie side You should set only redirect url, scopes and origin header settings. 
If you will receive any errors from Bungie, check your code and application settings.

**Comment by brianbolnick** [comment]
Thanks @RuBAN-GT! That's helpful. However, on the initial redirect to Bungie I keep getting an "Authorization query string parameters are not valid." error due to the client_id not being populated in the URL params. Here is an example request string:

```https://www.bungie.net/en/OAuth/Authorize?client_id&redirect_uri=https%3A%2F%2Fmyurl%3A3001%2Fusers%2Fauth%2Fbungie%2Fcallback&response_type=code&state=6a8720d4709be588b4bc83a42744f8fbef65136cadf75abb```

Notice `client_id` is blank. If I manually add `client_id=<id>` to the URL is redirects me to the right place and allows me to authorize. I've tried adding the client ID as a param but it doesn't look like that sticks either:

```<%= link_to "Sign in with Bungie", user_bungie_omniauth_authorize_path(:client_id=>'=<id>') %>```

Any thoughts?

**Comment by RuBAN-GT** [comment]
I find the cause: You can set `OAuth Client Type` on [the application settings page](https://www.bungie.net/en/Application), and the type changes the main ideas of authentication.

My URL string has another form with client type *"Not applicable"*: `https://www.bungie.net/en/Application/SignIn/11253?state...` and it doesn't use `client_id` field. May be when I created this gem this option was not implemented or I...skiped it) Then You should set *"Not applicable"* option and everything should work. If it's useful then I have working example with this gem: [https://grimoire.fydir.ru/](https://grimoire.fydir.ru/)

@brianbolnick, how do you think: for rails integration it's important difference between "Not applicable" and "Confidential"  methods?

**Comment by brianbolnick** [comment]
Ok that makes sense I got that piece working thanks for the input! Now I am gettin`ERROR -- omniauth: (bungie) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected` 

When going back to my app. What do you have set as your origin header? I am wondering if there is something else missing from the config.omniauth block @RuBAN-GT

**Comment by RuBAN-GT** [comment]
@brianbolnick, I set `*` in application Origin header field on the Bungie application page. In README I showed all settings for `config.omniauth`. I'll try to remake my code for "Confidential" method, because it's canonical Oauth2.

**Comment by RuBAN-GT** [comment]
@brianbolnick, I created the [dev brunch](https://github.com/RuBAN-GT/omniauth-bungie-oauth2/tree/dev), that changes oauth2 strategy. Please, change `OAuth Client Type` to **Confidential** and try to use a new version of gem from git.

**Comment by brianbolnick** [comment]
I'm still working off the master branch trying to fix this error:

```ERROR -- omniauth: (bungie) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected``` 

I've copied everything from your readme but the redirect from bungie back to my app is throwing that error @RuBAN-GT

**Comment by RuBAN-GT** [comment]
@brianbolnick, I upgrated this gem, now You can use bungie authentication without any problems. Please, read the README again (now, it has new description) and try reconfigure your settings.

**Comment by brianbolnick** [comment]
What are you using as the redirect_url? I currently have 

https://<url>/auth/bungie/callback

But am getting an invalid credentials error due to a mismatch of urls. I have the same url in my config as I do on bungie's app settings. @RuBAN-GT

**Comment by aetaric** [comment]
This should be re-opened. I see the same behavior above using OmniAuth::Builder. Other OmniAuth strategies are working without issue, just this one is misbehaving. I'm willing to provide any info requested to prove this is still broken.
